digital/urls.py
from django.contrib import admin
from django.urls import path, include
from store.views import staff 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'),),
    path('',staff.homepage,name='homepage'),
]

store/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import business, customer, staff


urlpatterns = [
    

    path('staff/', include(([
          path('paymentoptions/', staff.paymentoptions, name='paymentoptions'),
          path('returns/', staff.returns, name='returns'),
          path('register/', staff.register, name = 'register'),
          path('login/', staff.login, name = 'login'),
          path('logout/', staff.logout, name = 'logout'),
          path('update_user/', staff.update_user, name = 'update_user'),
          path('FAQS/', staff.FAQS,name='FAQS'),
          path('contact/', staff.contact,name='contact'),
          path('index/', staff.index,name='index'),
          path('about/', staff.about,name='about'),
          path('profile_redirect/', staff.profile_redirect, name = 'profile_redirect'),
          path('account/', staff.account, name = 'account'),
          path('homepage/',staff.homepage,name='homepage'),
          path('services', staff.services, name='services'),
          path('web_settings/', staff.web_settings, name='web_settings'),

      ],'store'), namespace='staff')),

    path('business/', include(([
          
          path('profile/', business.profile, name = 'profile'),
          path('dashboard',business.dashboard,name='dashboard'),
          path('businesscustomer/<str:pk>/',business.businesscustomer,name='businesscustomer'),
          path('upload',business.upload,name='upload'),
          path('updateProduct/<str:pk>/',business.updateProduct,name='updateProduct'),
          path('deleteProduct/<str:pk>/',business.deleteProduct,name='deleteProduct'),
      ],'store'), namespace='business')),
    
    path('customer/', include(([
        path('dashboard', customer.dashboard, name = 'dashboard'),
        path('profile/', customer.profile, name = 'profile'),
        path('product/<int:pk>',customer.product,name='product'),
        path ('category/<str:pa>',customer.category, name='category'),
        path('cart_summary',customer.cart_summary,name='cart_summary'),
        path('checkout/',customer.checkout, name='checkout'),
        path ('cart_add/',customer.cart_add, name='cart_add'),
        path ('cart_update/',customer.cart_update, name='cart_update'),
        path ('cart_delete/',customer.cart_delete, name='cart_delete'),
        path ('search_items/',customer.search_items, name='search'), #search
        path('languages/', customer.languages, name='languages'),
    
    
      ],'store'), namespace='customer')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

   

store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.contrib.postgres.fields import JSONField  # Import this for JSONField
from PIL import Image
from datetime import datetime

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class User(AbstractUser):
    class Types(models.TextChoices):
        BUSINESS = "BUSINESS", "BUSINESS"
        CUSTOMER = "CUSTOMER", "CUSTOMER"
    
    type = models.CharField(
        ('Type'), max_length=50, choices=Types.choices, default=Types.BUSINESS)
    
    name = models.CharField(("Name of User"), blank=True, max_length=225)
    
    # Custom fields for storing additional info
    custom_fields_for_business = models.JSONField(blank=True, null=True)
    custom_fields_for_customer = models.JSONField(blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

class BusinessManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.BUSINESS)

class CustomerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.CUSTOMER)

class CustomPermission(models.Model):
    BUSINESS_PERMISSIONS = [
        ('Can add products', 'Can delete products'),
        ('Can view products', 'Can update products'),
        
    ]

    CUSTOMER_PERMISSIONS = [
        ('can view products', 'Can select products'),
         ('can comment', 'Can make payment'),
    ]
    
    # Add a method to retrieve permissions based on user type
    @staticmethod
    def get_permissions_for_user_type(user_type):
        if user_type == User.Types.BUSINESS:
            return CustomPermission.BUSINESS_PERMISSIONS
        elif user_type == User.Types.CUSTOMER:
            return CustomPermission.CUSTOMER_PERMISSIONS
        else:
            return []

class Business(User):
    objects = BusinessManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.BUSINESS
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Customer(User):
    objects = CustomerManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.CUSTOMER
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class StaffUser(User):
    class Meta:
        proxy = True

    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    class Meta:
        
        verbose_name_plural = 'categories'
class Product(models.Model):
    
    image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=200, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(Category,null=True, on_delete=models.SET_NULL, default=1)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name
    
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=" "
        return url
    
    
    
class Comment(models.Model):
    product = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    commenter_name = models.CharField(max_length=200)
    comment_body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.product.name, self.commenter_name)




    
class Order(models.Model):
    
   
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=True)
    transaction_id=models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    
class OrderItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity=models.IntegerField(default=0,null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
       total = self.product.price * self.quantity
       return total 



class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address=models.CharField(max_length=200,null=False) 
    district=models.CharField(max_length=200,null=False)
    town=models.CharField(max_length=200,null=False)
    
    def __str__(self) -> str:
        return self.address

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    telephone = models.CharField(max_length=10, blank=False)
    website = models.CharField(max_length=70, blank=False)
    business_name = models.CharField(max_length=20, blank=False)
    category = models.CharField(max_length=50, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    pobox = models.CharField(max_length=10, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
    bio = models.CharField(default='', max_length=400, blank=True)
    
    def __str__(self):
        return f'{self.user.username} Profile'
    

class Customer_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
  
    
    def __str__(self):
        return f'{self.user.username} Profile'
    
    

store/forms.py
       
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from .models import *
from django.forms import ModelForm
from django import forms
from .models import Contact
# If you're using Django's built-in User model
# from django.contrib.auth.models import User

User = get_user_model()

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'type', 'name')  # Add custom fields here

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True
        

class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = '__all__'  # This will include all fields of the user model

    def __init__(self, *args, **kwargs):
        super(MyUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=15)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    type = forms.CharField(label='Type')  # Add 'type' field to the form

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'type']  # Include 'password1' and 'password2'

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.type = self.cleaned_data["type"]
        if commit:
            user.save()
        return user




class ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    telephone = forms.CharField(label = 'telephone')
    website = forms.CharField(label = 'website')
    business_name = forms.CharField(label = 'business_name')
    category = forms.CharField(label = 'category')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    pobox = forms.CharField(label = 'pobox')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
    bio = forms.CharField(label = 'bio')
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'telephone','website','business_name','category', 'address_line_1', 'address_line_2', 'pobox', 'street', 'state', 'zip_code', 'bio')
        
        
class Customer_ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
  
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'address_line_1', 'address_line_2', 'street', 'state', 'zip_code')
        

class UploadForm(forms.ModelForm):
    name = forms.TextInput()
    price = forms.DecimalField()
    image = forms.ImageField()
    description = forms.TextInput()
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = Product
        fields = ['name', 'price', 'image', 'description', 'category']
        

User = get_user_model()

store/views/business.py
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from ..models import Profile
from django.core.exceptions import ObjectDoesNotExist
from store.backends import User
from ..forms import ProfileForm
from store.models import *
from store.forms import *
 

@login_required
def profile(request):
    profile = None
    try:
        profile = request.user.profile
        form = ProfileForm(instance=profile)
    except ObjectDoesNotExist:
        profile = None
        form = ProfileForm()

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('staff:account')

    return render(request, 'business/Profile.html', {'form': form, 'profile': profile})

@login_required
# @admin_only
def dashboard(request):
    products = Product.objects.all()
    customers = Customer.objects.all()
    orders = Order.objects.all()
    total_orders = orders.count()
    total_products = products.count()
    total_customers = customers.count()
    
    
    context = {'products':products,'customers':customers,'total_products':total_products,'total_customers':total_customers,'total_orders':total_orders}
    templates = loader.get_template('business/dashboard.html')
    return render(request,'business/dashboard.html',context)



@login_required
# @admin_only
def businesscustomer(request,pk):
    customer = Customer.objects.get(id = pk)
    orders = customer.order_set.all()
    templates = loader.get_template('business/businesscustomer.html')
    context ={
        'customer':customer,
        'orders':orders
    }
    return render(request, 'business/businesscustomer.html',context)


def upload(request):
    if request.POST:
        forms = UploadForm(request.POST, request.FILES)
        print(request.FILES)
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    return render(request, 'business/upload.html',{'form': UploadForm})

def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    form = UploadForm(instance=product)
    if request.POST:
        forms = UploadForm(request.POST, instance=product)
        
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    context = {'form': form}
    return render(request, 'business/upload.html',context)

def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method =='POST':
        product.delete()
        return redirect('business:dashboard')
    context ={'product':product}
    return render(request, 'business/delete.html',context)

store/templates/staff/login.html
{% extends 'staff/master.html' %}
{% load static %}


{%block title%}Login{%endblock%}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<style>
    body{
        background: url('{% static "img\login.jpg" %}') no-repeat;/* for the image*/
        background-size: cover;
        background-position: center;
    }
    .login{
        opacity: 0.9;
        transform: translateX(-200px);
    }
    .reg a{
        color: blue;
        padding-left: 20px;
        margin-left: 20px;
    }

    /* footer css */
    .footer {
    background-color: #3333336c;
    color: bisque;
    padding: 50px 0;
    outline: none;
}

.container-footer {
    max-width: 1100px;
    margin: 0 auto;
}

.row {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

.footer-col {
    width: 25%;
    padding: 0 15px;
}

.footer-col h4 {
    font-size: 18px;
    margin-bottom: 20px;
}

.footer-col ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
}

.footer-col ul li {
    margin-bottom: 10px;
}

.footer-col ul li a {
    color: #fff;
    text-decoration: none;
    font-size: 15px;
    
}

.footer-col ul li a:hover {
    text-decoration: underline;
}

.social-links a {
    color: #fff;
    font-size: 24px;
    margin-right: 10px;
    transition: color 0.3s ease;
}

.social-links a:hover {
    color: #cccccc;
}


    /* Media queries for responsiveness */

/* Styles for small devices (e.g., smartphones) */
@media only screen and (max-width: 767px) {
    .login {
        opacity: 0.9; /* Retain opacity */
        transform: none; /* Remove transformation */
        margin: 0 auto; /* Center horizontally */
        width: 90%; /* Adjust width as needed */
        max-width: 400px; /* Adjust max-width as needed */
        padding: 20px; /* Add padding for spacing */
    }

    .form-group label {
        font-size: 16px; /* Adjust label font size */
    }

    .form-control {
        width: 100%; /* Make inputs full width */
        margin-bottom: 15px; /* Add spacing between inputs */
        padding: 10px; /* Increase input padding */
        font-size: 16px; /* Adjust input font size */
    }

    .submit-button {
        width: 100%; /* Make button full width */
        font-size: 16px; /* Adjust button font size */
        margin: -1%;
    }

    .reg a {
        font-size: 16px; /* Adjust link font size */
    }
    .footer {
        padding: 30px 0;
    }

    .footer-col {
        width: 100%;
        margin-bottom: 20px;
    }

    .footer-col h4 {
        font-size: 16px;
        margin-bottom: 15px;
    }

    .footer-col ul li a {
        font-size: 14px;
    }

    .social-links a {
        font-size: 20px;
    }

    small {
        font-size: 12px;
    }
    .footer-col {
        width: 50%;
        margin-bottom: 30px;
    }
}
.submit-button {
    width: 100%; /* Make button full width */
    font-size: 16px; /* Adjust button font size */
    margin: -1%;
}

/* Styles for extra small devices (e.g., smaller smartphones) */
@media only screen and (max-width: 574px) {
    .login {
        width: 90%; /* Adjust width for smaller devices */
        max-width: 300px; /* Adjust max-width for smaller devices */
    }

    .form-group label,
    .form-control {
        font-size: 14px; /* Further reduce font size for smaller devices */
    }

    .submit-button,
    .reg a {
        font-size: 14px; /* Further reduce font size for smaller devices */
    }

    .footer {
        background-color: #3333336c;
        color: bisque;
        padding: 50px 0;
        text-align: center;
    }

    .container-footer {
        max-width: 1100px;
        margin: 0 auto;
    }

    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .footer-col {
        width: 25%;
        padding: 0 15px;
    }

    .footer-col h4 {
        font-size: 18px;
        margin-bottom: 20px;
    }

    .footer-col ul {
        list-style-type: none;
        padding: 0;
        margin: 0;
        display: flex;
        flex-direction: column;
    }

    .footer-col ul li {
        margin-bottom: 10px;
    }

    .footer-col ul li a {
        color: #fff;
        text-decoration: none;
        font-size: 15px;
    }

    .footer-col ul li a:hover {
        text-decoration: underline;
    }

    .social-links a {
        color: #fff;
        font-size: 24px;
        margin-right: 10px;
        transition: color 0.3s ease;
    }

    .social-links a:hover {
        color: #cccccc;
    }

    small {
        font-size: 12px;
    }

    .custom-message {
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 5px;
    }
    
    .custom-message.error {
        background-color: #f8d7da;
        color: #721c24;
    }
    
    .custom-message.success {
        background-color: #d4edda;
        color: #155724;
    }
    
    .custom-message.warning {
        background-color: #fff3cd;
        color: #856404;
    }
    
    .custom-message.info {
        background-color: #d1ecf1;
        color: #0c5460;
    }
    
}

    
</style>


<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'staff:homepage' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:register'%}">REGISTER</a></li>
    </ul>
</nav>

{% for message in messages %}
<div class="custom-message {% if message.tags %}{{ message.tags }}{% endif %}">
    {{ message }}
</div>
{% endfor %}

<div class="login">

    {% comment %} <h2>Register Page</h2> {% endcomment %}


    <form method="POST">
        {% csrf_token %}
                
        
    <div class="form-group">
    <label for="username">Username</label>
    <input type="text" name="username" class="form-control" required>
    </div>

    <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control" required>
    </div>

    <input type="submit" value="Login" class="submit-button">

    </form>
</div>



<div class="reg">
    <p class = "text-align">Create an account?  <a href="{% url 'staff:register' %}"><strong>Register</strong></a></p>
</div>

<footer class="footer">
    <div class="container-footer">
        <div class="row">

            
            <div class="footer-col">
                <h4>Ecomserver</h4>
                <ul>
                    <li><a href="{% url 'staff:about' %}">About Us</a></li>
                    <li><a href="{% url 'staff:services' %}">Our Services</a></li>
                    {% comment %} <li><a href="{% url 'privacy_policy' %}">Privacy Policy</a></li> {% endcomment %}
                    <li><a href="{% url 'staff:contact' %}">Contact</a></li>
                </ul>
            </div>

            <div class="footer-col">
                <h4>Get Help</h4>
                <ul>
                    <li><a href="{% url 'staff:FAQS'%}">FAQ</a></li>
                    <li><a href="{% url 'staff:returns'%}">Returns</a></li>
                    <li><a href="{% url 'staff:paymentoptions' %}">Payment Options</a></li>
                </ul>
            </div>

            <div class="footer-col">
                <h4>Online Shop</h4>
                <ul>
                    <li><a href='{% url "customer:category" 'Electronics' %}'>Electronics</a></li>
                    <li><a href='{% url "customer:category" 'Clothes' %}'>Fashion</a></li>
                    <li><a href='{% url "customer:category" 'Funiture' %}'>Furniture</a></li>
                    <li><a href='{% url "customer:category" 'Bags' %}'>Bags</a></li>
                    <li><a href='{% url "customer:category" 'Phones' %}'>Phones</a></li>
                    <li><a href='{% url "customer:category" 'Groceries' %}'>Groceries</a></li>
                    <li><a href='{% url "customer:category" 'Sports' %}'>Sports</a></li>
                    <li><a href='{% url "customer:category" 'Health' %}'>Health</a></li>
                    <li><a href='{% url "customer:category" 'Stationery' %}'>Stationary</a></li>
                    
                </ul>
            </div>

            <div class="footer-col">
                <h4>Follow Us</h4>
                <div class="social-links">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                </div>
            </div>
        </div>
        <small>&copy; 2024 Ecomserver.  <br>All rights reserved.</small>
    </div>
</footer>

{% endblock %}

store/templates/staff/logout.html
{% extends 'staff/master.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <button type="submit" class="logout-button">Logout</button>
  </form>

  {% endblock %}

store/templates/staff/update_user.html
{% extends 'staff/master.html' %}
{%load static%}

{%block title%}Personal Information{%endblock%}


{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'staff:homepage' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:account'%}">PROFILE</a></li>
    </ul>
</nav>


<div class = 'update'>
<form method="post" action="{% url 'staff:update_user' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" value="{{ user.username }}" required>
    <br></br>
    <label for="first_name">First Name:</label>
    <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}" required>
    <br></br>
    <label for="last_name">Last Name:</label>
    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}" required>
    <br></br>
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" value="{{ user.email }}" required>
    <br></br>
    <button type="submit">Save</button>
</form>
</div>
{% endblock %}