digital/urls.py
from django.contrib import admin
from django.urls import path, include
from store.views import staff 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'),),
    path('',staff.homepage,name='homepage'),
]

store/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import business, customer, staff


urlpatterns = [
    

    path('staff/', include(([
          path('paymentoptions/', staff.paymentoptions, name='paymentoptions'),
          path('returns/', staff.returns, name='returns'),
          path('register/', staff.register, name = 'register'),
          path('login/', staff.login, name = 'login'),
          path('logout/', staff.logout, name = 'logout'),
          path('update_user/', staff.update_user, name = 'update_user'),
          path('FAQS/', staff.FAQS,name='FAQS'),
          path('contact/', staff.contact,name='contact'),
          path('index/', staff.index,name='index'),
          path('about/', staff.about,name='about'),
          path('profile_redirect/', staff.profile_redirect, name = 'profile_redirect'),
          path('account/', staff.account, name = 'account'),
          path('homepage/',staff.homepage,name='homepage'),
          path('services', staff.services, name='services'),
          path('web_settings/', staff.web_settings, name='web_settings'),

      ],'store'), namespace='staff')),

    path('business/', include(([
          
          path('profile/', business.profile, name = 'profile'),
          path('dashboard',business.dashboard,name='dashboard'),
          path('businesscustomer/<str:pk>/',business.businesscustomer,name='businesscustomer'),
          path('upload',business.upload,name='upload'),
          path('updateProduct/<str:pk>/',business.updateProduct,name='updateProduct'),
          path('deleteProduct/<str:pk>/',business.deleteProduct,name='deleteProduct'),
      ],'store'), namespace='business')),
    
    path('customer/', include(([
        path('dashboard', customer.dashboard, name = 'dashboard'),
        path('profile/', customer.profile, name = 'profile'),
        path('product/<int:pk>',customer.product,name='product'),
        path ('category/<str:pa>',customer.category, name='category'),
        path('cart_summary',customer.cart_summary,name='cart_summary'),
        path('checkout/',customer.checkout, name='checkout'),
        path ('cart_add/',customer.cart_add, name='cart_add'),
        path ('cart_update/',customer.cart_update, name='cart_update'),
        path ('cart_delete/',customer.cart_delete, name='cart_delete'),
        path ('search_items/',customer.search_items, name='search'), #search
        path('languages/', customer.languages, name='languages'),
    
    
      ],'store'), namespace='customer')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

   

store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.contrib.postgres.fields import JSONField  # Import this for JSONField
from PIL import Image
from datetime import datetime

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class User(AbstractUser):
    class Types(models.TextChoices):
        BUSINESS = "BUSINESS", "BUSINESS"
        CUSTOMER = "CUSTOMER", "CUSTOMER"
    
    type = models.CharField(
        ('Type'), max_length=50, choices=Types.choices, default=Types.BUSINESS)
    
    name = models.CharField(("Name of User"), blank=True, max_length=225)
    
    # Custom fields for storing additional info
    custom_fields_for_business = models.JSONField(blank=True, null=True)
    custom_fields_for_customer = models.JSONField(blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

class BusinessManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.BUSINESS)

class CustomerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.CUSTOMER)

class CustomPermission(models.Model):
    BUSINESS_PERMISSIONS = [
        ('Can add products', 'Can delete products'),
        ('Can view products', 'Can update products'),
        
    ]

    CUSTOMER_PERMISSIONS = [
        ('can view products', 'Can select products'),
         ('can comment', 'Can make payment'),
    ]
    
    # Add a method to retrieve permissions based on user type
    @staticmethod
    def get_permissions_for_user_type(user_type):
        if user_type == User.Types.BUSINESS:
            return CustomPermission.BUSINESS_PERMISSIONS
        elif user_type == User.Types.CUSTOMER:
            return CustomPermission.CUSTOMER_PERMISSIONS
        else:
            return []

class Business(User):
    objects = BusinessManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.BUSINESS
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Customer(User):
    objects = CustomerManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.CUSTOMER
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class StaffUser(User):
    class Meta:
        proxy = True

    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    class Meta:
        
        verbose_name_plural = 'categories'
class Product(models.Model):
    
    image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=200, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(Category,null=True, on_delete=models.SET_NULL, default=1)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name
    
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=" "
        return url
    
    
    
class Comment(models.Model):
    product = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    commenter_name = models.CharField(max_length=200)
    comment_body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.product.name, self.commenter_name)




    
class Order(models.Model):
    
   
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=True)
    transaction_id=models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    
class OrderItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity=models.IntegerField(default=0,null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
       total = self.product.price * self.quantity
       return total 



class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address=models.CharField(max_length=200,null=False) 
    district=models.CharField(max_length=200,null=False)
    town=models.CharField(max_length=200,null=False)
    
    def __str__(self) -> str:
        return self.address

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    telephone = models.CharField(max_length=10, blank=False)
    website = models.CharField(max_length=70, blank=False)
    business_name = models.CharField(max_length=20, blank=False)
    category = models.CharField(max_length=50, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    pobox = models.CharField(max_length=10, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
    bio = models.CharField(default='', max_length=400, blank=True)
    
    def __str__(self):
        return f'{self.user.username} Profile'
    

class Customer_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
  
    
    def __str__(self):
        return f'{self.user.username} Profile'
    
    

store/forms.py
       
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from .models import *
from django.forms import ModelForm
from django import forms
from .models import Contact
# If you're using Django's built-in User model
# from django.contrib.auth.models import User

User = get_user_model()

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'type', 'name')  # Add custom fields here

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True
        

class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = '__all__'  # This will include all fields of the user model

    def __init__(self, *args, **kwargs):
        super(MyUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=15)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    type = forms.CharField(label='Type')  # Add 'type' field to the form

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'type']  # Include 'password1' and 'password2'

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.type = self.cleaned_data["type"]
        if commit:
            user.save()
        return user




class ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    telephone = forms.CharField(label = 'telephone')
    website = forms.CharField(label = 'website')
    business_name = forms.CharField(label = 'business_name')
    category = forms.CharField(label = 'category')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    pobox = forms.CharField(label = 'pobox')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
    bio = forms.CharField(label = 'bio')
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'telephone','website','business_name','category', 'address_line_1', 'address_line_2', 'pobox', 'street', 'state', 'zip_code', 'bio')
        
        
class Customer_ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
  
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'address_line_1', 'address_line_2', 'street', 'state', 'zip_code')
        

class UploadForm(forms.ModelForm):
    name = forms.TextInput()
    price = forms.DecimalField()
    image = forms.ImageField()
    description = forms.TextInput()
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = Product
        fields = ['name', 'price', 'image', 'description', 'category']
        

User = get_user_model()

store/views/business.py
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from ..models import Profile
from django.core.exceptions import ObjectDoesNotExist
from store.backends import User
from ..forms import ProfileForm
from store.models import *
from store.forms import *
 

@login_required
def profile(request):
    profile = None
    try:
        profile = request.user.profile
        form = ProfileForm(instance=profile)
    except ObjectDoesNotExist:
        profile = None
        form = ProfileForm()

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('staff:account')

    return render(request, 'business/Profile.html', {'form': form, 'profile': profile})

@login_required
# @admin_only
def dashboard(request):
    products = Product.objects.all()
    customers = Customer.objects.all()
    orders = Order.objects.all()
    total_orders = orders.count()
    total_products = products.count()
    total_customers = customers.count()
    
    
    context = {'products':products,'customers':customers,'total_products':total_products,'total_customers':total_customers,'total_orders':total_orders}
    templates = loader.get_template('business/dashboard.html')
    return render(request,'business/dashboard.html',context)



@login_required
# @admin_only
def businesscustomer(request,pk):
    customer = Customer.objects.get(id = pk)
    orders = customer.order_set.all()
    templates = loader.get_template('business/businesscustomer.html')
    context ={
        'customer':customer,
        'orders':orders
    }
    return render(request, 'business/businesscustomer.html',context)


def upload(request):
    if request.POST:
        forms = UploadForm(request.POST, request.FILES)
        print(request.FILES)
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    return render(request, 'business/upload.html',{'form': UploadForm})

def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    form = UploadForm(instance=product)
    if request.POST:
        forms = UploadForm(request.POST, instance=product)
        
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    context = {'form': form}
    return render(request, 'business/upload.html',context)

def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method =='POST':
        product.delete()
        return redirect('business:dashboard')
    context ={'product':product}
    return render(request, 'business/delete.html',context)

store/templates/business/Profile.html
{% extends "staff/master.html" %}
{%load static%}

{%block title%} Profile {%endblock%}

{% block content %} 

<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'business:dashboard' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:account'%}">PROFILE</a></li>
    </ul>
</nav>

<div class = 'business'>
<div class = 'business1'>
<form method="post" action="{% url 'business:profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class = 'circular-image'>
    {{ form.non_field_errors }}
    {% if user.profile.image %}
        <img src="{{ user.profile.image.url }}" alt="Profile Image">
    {% endif %}
    {{ form.image }} 
    </div> 
    <label for="id_image">Upload Photo:</label> 
    <input type="file" id="id_image" name="image" accept="image/*">
    <br></br>
    <label for="id_gender">Gender:</label>
    {{ form.gender }}
    <br></br>
    <label for="id_contact">Contact:</label> 
    {{ form.contact }}
    <br></br>
    <label for="id_telephone">Telephone Number:</label>
    {{ form.telephone}}
    <br></br>
    <label for="id_website">Website:</label> 
    {{ form.website }}
    <br></br>
    <label for="id_business_name">Business Name:</label>
    {{ form.business_name }}
    <br></br> 
</div>
<div class = 'business2'> 
    <p><font size = '5'>Business</font></p>
    <label for="id_category">Category:</label>
    {{ form.category }}
    <br></br>
    <label for="id_address_liane_1">Address Line 1:</label>
    {{ form.address_line_1 }}
    <br></br>
    <label for="id_address_liane_2">Address Line 2:</label>
    {{ form.address_line_2 }}
    <br></br>
    <label for="id_pobox">P.O. Box:</label>
    {{ form.pobox }}
    <br></br>
    <label for="id_street">Street:</label>
    {{ form.street }}
    <br></br>
    <label for="id_state">State:</label>
    {{ form.state }}
    <br></br>
    <label for="id_zip_code">Zip_Code:</label>
    {{ form.zip_code }}
    <br></br>
    <label for="id_bio">Bio:</label>
    {{ form.bio }}
    <br></br>
</div>
<br></br>
<button type="submit" class = 'submit-button'>Save</button>

</form>
</div>

{% endblock %}

store/templates/business/account.html
{%extends 'staff/master.html'%}
{%load static%}

    {%block title%}
    ACCOUNT
    {%endblock%}


{%block content%}

<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'business:dashboard' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:account'%}">PROFILE</a></li>
    </ul>
</nav>

<div class = 'account'> 
        <div class = "account_user">    
        <div class="account_info">
        
        <div class = "circular-image">
        <img src="{{ profile.image.url }}" alt="Profile Image">
        </div>
        <br>
        <p class="address-text">Email: {{ email }}</p>
        <br>
        <p class="address-text">Name: {{ first_name }} {{ last_name }}</p>
        <br>
        <p class="address-text">Username: {{username}}</p>
        </div>

        
        <div class="account_personal">  
        <p><font size = '9' color = 'orange'>Personal</font></p>
      
        <p class="large-text">Date of Birth: {{ profile.date_of_birth }}</p>
        <br>
        <p class="large-text">Gender: {{ profile.gender }}</p>
        <br>
        <p class="large-text">Contact: {{ profile.contact }}</p>
        <br>
        <p class="large-text">Telephone: {{ profile.telephone }}</p>
        <br>
        <p class="large-text">Zip Code: {{ profile.zip_code }}</p>
        </div>
        </div>
        
        <div class = "account_bus">
        <div class="account_business">  
        <p><font size = '6' color = 'orange'>Business Info</font></p>
        <br>
        <p class="bus-text">Business Name: {{ profile.business_name }}</p>
        <br>
        <p class="bus-text">Website: {{ profile.website }}</p>
        <br>
        <p class="bus-text">Category: {{ profile.category }}</p>
        <br>
        <p class="bus-text">Bio: {{ profile.bio}}</p>
        </div>

        <div class = "account_address ">
        <p><font size = '14' color = 'orange'>Address</font></p>
        <p class="address-text">Address Line 1: {{ profile.address_line_1 }}</p>
        <br>
        <p class="address-text">Address Line 2: {{ profile.address_line_2 }}</p>
        <br>
        <p class="address-text">P.O. Box: {{ profile.pobox }}</p>
        <br>
        <p class="address-text">Street: {{ profile.street }}</p>
        <br>
        <p class="address-text">State: {{ profile.state }}</p>
        </div>
        </div>
    
    <a href="{% url 'staff:update_user' %}"><button type="submit"  class = "submit-account">Edit Profile</button></a>
</div>
{%endblock%}


       

       

store/templates/business/business.html
{% extends 'staff/master.html' %}

{% block content %}

  <h2>Sign up for a business</h2>
  <p class="lead">Select below the type of account you want to create</p>

{% endblock %}

store/templates/business/businesscustomer.html
{% extends "business/businessmain.html" %}
{% block content %}
<div class='row'>

    <div class='col-md'>
        <div class ='card card-body'>
            <img src="{{ customer.profile.image.url }}" alt="Profile Image">
        </div>
    </div>
    
    <div class='col-md'>
        <div class ='card card-body'>
            <h5>Customer: {{customer.first_name}} {{customer.last_name}}</h5>
            <h5>Customer: {{customer.username}}</h5>
            <hr>
            
            <a class ='btn btn-outline-danger btn-sm btn-block' href=''>Delete Customer</a>
        </div>
    </div>

    <div class='col-md'>
        <div class ='card card-body'>
            <h5>Contact Information</h5>
            <hr>
            <p>Email:  {{customer.email}} </p>
            <p>Phone:  {{customer.profile.contact}} </p>
            <p>Location: {{customer.profile.street}},  {{customer.profile.state}} </p>
        </div>
    </div>
    
</div>
<br>


{% endblock  %}

store/templates/business/businessnavbar.html
{% load static %}
<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">eCOMServer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'business:dashboard' %}">Dashboard<span class="sr-only"></span></a>
      <a class="nav-item nav-link" href="{% url 'business:upload' %}">Upload_Products</a>
      
      
     
      
    </div>
  </div>
  <span class='hello-msg'>Hello, {{request.user}} </span>
  <a class='hello-msg' href='{% url 'staff:account'%}'><ion-icon name='person-outline'></ion-icon>Profile</a>
  <span><a class='hello-msg' href="/staff/login">Logout</a><span>
</nav>

store/templates/business/dashboard.html
{% extends "business/businessmain.html" %}
{% block content %}

{% include "business/businessstatus.html" %}
<div class = 'row'>
    <div class = 'col-md-5'>
        <h5>eCOMServer</h5>
        <hr>
        <div class ='card card-body'>
            <a class= 'btn btn-primary bt-sm btn-block' href=''>Customer</a>
            <table class= 'table table-sm'>
                <tr>
                    <th></th>
                    <th>Customer</th>
                    <th>Phone</th>
                </tr>

                {% for customer in customers %}
                  <tr>
                    <td><a class= 'btn btn-sm btn-info'href ='{% url "business:businesscustomer" customer.id %}'>View</a></td>
                    <td>{{customer.username}}</td>
                    
                    <td>{{customer.email}}</td>
                  </tr>


                {% endfor %}
                
            </table>
        </div>
    </div>

    <div class= 'col-md-7'>
        <h5>We are here to serve you</h5>
        <hr>
        <div class='card card-body'>
            <a class= 'btn btn-primary bt-sm btn-block' href=''>Product Details</a>
            <table class= 'table table-sm'>
                <tr>
                    
                    <th>Product</th>
                    <th>Price</th>
                    
                    <th>Update</th>
                    <th>Remove</th>
                </tr>

                {% for product in products %}
                  <tr>
                    <td>{{product.name}}</td>
                    <td>{{product.price}}</td>
                    
                    <td><a class= 'btn btn-sm btn-info' href='{% url 'business:updateProduct' product.id %}'>Update</a></td>
                    <td><a class= 'btn btn-sm btn-danger'  href ='{% url 'business:deleteProduct' product.id %}'>Delete</a></td>
                  </tr>


                {% endfor %}
            </table>
        </div>
    </div>
</div>


{% endblock  %}

store/templates/business/delete.html
{% extends "business/businessmain.html" %}
{% block content %}

<p>Are you sure you want to delete?</p>
{{product.imageURL}}
<br>
{{product.name}}
{{product.price}}

<form action='{% url 'business:deleteProduct' product.id %}'method ='POST'>
    
    {% csrf_token %}
    <a href='{% url "business:dashboard" %}'>Cancel</a>

    <input type='submit' name='Confirm'>
</form>

{% endblock %}

store/templates/business/upload.html
{% extends 'business/businessmain.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-5">Business Product Upload Page</h1>

    <form method="POST" action="{% url 'business:upload' %}" enctype="multipart/form-data" class="row g-3">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="id_name" class="form-label">Name</label>
            <input type="text" class="form-control" id="id_name" name="{{ form.name.name }}" placeholder="Enter your product name" required>
        </div>
        <div class="col-md-6">
            <label for="id_price" class="form-label">Price</label>
            <input type="number" class="form-control" id="id_price" name="{{ form.price.name }}" placeholder="Enter your product price" required>
        </div>
        <br><br><br><br>
        <div class="col-md-6">
            <label for="id_category" class="form-label">Category</label>
            <select class="form-control" id="id_category" name="{{ form.category.name }}" required>
                <option value="{{ form.category.initial }}">{{ form.category.initial }}</option>
                {% for category in form.category.field.queryset %}
                    {% if category.name != form.category.initial %}
                        <option value="{{ category.pk }}">{{ category.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <br><br><br><br>
        <div class="col-md-6">
            <label for="id_image" class="form-label">Image</label>
            {{ form.image }}
        </div>
        <div class="col-12">
            <label for="id_description" class="form-label">Description</label>
            <textarea class="form-control" id="id_description" name="{{ form.description.name }}" placeholder="Enter your description" required></textarea>
        </div>

        <br> <br><br><br><br>

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href='/business/dashboard'><button type="button" class="btn btn-secondary" onclick="goBack()">Back</button></a>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}