digital/urls.py
from django.contrib import admin
from django.urls import path, include
from store.views import staff 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'),),
    path('',staff.homepage,name='homepage'),
]

store/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import business, customer, staff


urlpatterns = [
    

    path('staff/', include(([
          path('paymentoptions/', staff.paymentoptions, name='paymentoptions'),
          path('returns/', staff.returns, name='returns'),
          path('register/', staff.register, name = 'register'),
          path('login/', staff.login, name = 'login'),
          path('logout/', staff.logout, name = 'logout'),
          path('update_user/', staff.update_user, name = 'update_user'),
          path('FAQS/', staff.FAQS,name='FAQS'),
          path('contact/', staff.contact,name='contact'),
          path('index/', staff.index,name='index'),
          path('about/', staff.about,name='about'),
          path('profile_redirect/', staff.profile_redirect, name = 'profile_redirect'),
          path('account/', staff.account, name = 'account'),
          path('homepage/',staff.homepage,name='homepage'),
          path('services', staff.services, name='services'),
          path('web_settings/', staff.web_settings, name='web_settings'),

      ],'store'), namespace='staff')),

    path('business/', include(([
          
          path('profile/', business.profile, name = 'profile'),
          path('dashboard',business.dashboard,name='dashboard'),
          path('businesscustomer/<str:pk>/',business.businesscustomer,name='businesscustomer'),
          path('upload',business.upload,name='upload'),
          path('updateProduct/<str:pk>/',business.updateProduct,name='updateProduct'),
          path('deleteProduct/<str:pk>/',business.deleteProduct,name='deleteProduct'),
      ],'store'), namespace='business')),
    
    path('customer/', include(([
        path('dashboard', customer.dashboard, name = 'dashboard'),
        path('profile/', customer.profile, name = 'profile'),
        path('product/<int:pk>',customer.product,name='product'),
        path ('category/<str:pa>',customer.category, name='category'),
        path('cart_summary',customer.cart_summary,name='cart_summary'),
        path('checkout/',customer.checkout, name='checkout'),
        path ('cart_add/',customer.cart_add, name='cart_add'),
        path ('cart_update/',customer.cart_update, name='cart_update'),
        path ('cart_delete/',customer.cart_delete, name='cart_delete'),
        path ('search_items/',customer.search_items, name='search'), #search
        path('languages/', customer.languages, name='languages'),
    
    
      ],'store'), namespace='customer')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

   

store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.contrib.postgres.fields import JSONField  # Import this for JSONField
from PIL import Image
from datetime import datetime

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class User(AbstractUser):
    class Types(models.TextChoices):
        BUSINESS = "BUSINESS", "BUSINESS"
        CUSTOMER = "CUSTOMER", "CUSTOMER"
    
    type = models.CharField(
        ('Type'), max_length=50, choices=Types.choices, default=Types.BUSINESS)
    
    name = models.CharField(("Name of User"), blank=True, max_length=225)
    
    # Custom fields for storing additional info
    custom_fields_for_business = models.JSONField(blank=True, null=True)
    custom_fields_for_customer = models.JSONField(blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

class BusinessManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.BUSINESS)

class CustomerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.CUSTOMER)

class CustomPermission(models.Model):
    BUSINESS_PERMISSIONS = [
        ('Can add products', 'Can delete products'),
        ('Can view products', 'Can update products'),
        
    ]

    CUSTOMER_PERMISSIONS = [
        ('can view products', 'Can select products'),
         ('can comment', 'Can make payment'),
    ]
    
    # Add a method to retrieve permissions based on user type
    @staticmethod
    def get_permissions_for_user_type(user_type):
        if user_type == User.Types.BUSINESS:
            return CustomPermission.BUSINESS_PERMISSIONS
        elif user_type == User.Types.CUSTOMER:
            return CustomPermission.CUSTOMER_PERMISSIONS
        else:
            return []

class Business(User):
    objects = BusinessManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.BUSINESS
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Customer(User):
    objects = CustomerManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.CUSTOMER
        return super().save(*args, **kwargs)
    
    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class StaffUser(User):
    class Meta:
        proxy = True

    def get_permissions(self):
        return CustomPermission.get_permissions_for_user_type(self.type)

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    class Meta:
        
        verbose_name_plural = 'categories'
class Product(models.Model):
    
    image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=200, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(Category,null=True, on_delete=models.SET_NULL, default=1)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name
    
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=" "
        return url
    
    
    
class Comment(models.Model):
    product = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    commenter_name = models.CharField(max_length=200)
    comment_body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.product.name, self.commenter_name)




    
class Order(models.Model):
    
   
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=True)
    transaction_id=models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    
class OrderItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity=models.IntegerField(default=0,null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
       total = self.product.price * self.quantity
       return total 



class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address=models.CharField(max_length=200,null=False) 
    district=models.CharField(max_length=200,null=False)
    town=models.CharField(max_length=200,null=False)
    
    def __str__(self) -> str:
        return self.address

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    telephone = models.CharField(max_length=10, blank=False)
    website = models.CharField(max_length=70, blank=False)
    business_name = models.CharField(max_length=20, blank=False)
    category = models.CharField(max_length=50, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    pobox = models.CharField(max_length=10, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
    bio = models.CharField(default='', max_length=400, blank=True)
    
    def __str__(self):
        return f'{self.user.username} Profile'
    

class Customer_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default_pic.jpg', upload_to="profile_pics")
    gender = models.CharField(default='', max_length=10, blank=False)
    contact = models.CharField(max_length=10, blank=False)
    address_line_1 = models.CharField(max_length=100, blank=False)
    address_line_2 = models.CharField(max_length=100, blank=False)
    street = models.CharField(max_length=10, blank=False)
    state = models.CharField(max_length=50, blank=False)
    zip_code = models.CharField(max_length=10, blank=False)
  
    
    def __str__(self):
        return f'{self.user.username} Profile'
    
    

store/forms.py
       
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from .models import *
from django.forms import ModelForm
from django import forms
from .models import Contact
# If you're using Django's built-in User model
# from django.contrib.auth.models import User

User = get_user_model()

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'type', 'name')  # Add custom fields here

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True
        

class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = '__all__'  # This will include all fields of the user model

    def __init__(self, *args, **kwargs):
        super(MyUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = True
        self.fields['name'].required = True


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=15)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    type = forms.CharField(label='Type')  # Add 'type' field to the form

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'type']  # Include 'password1' and 'password2'

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.type = self.cleaned_data["type"]
        if commit:
            user.save()
        return user




class ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    telephone = forms.CharField(label = 'telephone')
    website = forms.CharField(label = 'website')
    business_name = forms.CharField(label = 'business_name')
    category = forms.CharField(label = 'category')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    pobox = forms.CharField(label = 'pobox')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
    bio = forms.CharField(label = 'bio')
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'telephone','website','business_name','category', 'address_line_1', 'address_line_2', 'pobox', 'street', 'state', 'zip_code', 'bio')
        
        
class Customer_ProfileForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    gender = forms.CharField(label = 'gender')
    contact = forms.CharField(label = 'contact')
    address_line_1 = forms.CharField(label = 'address_line_1')
    address_line_2 = forms.CharField(label = ' address_line_2')
    street = forms.CharField(label = 'street')
    state = forms.CharField(label = 'state')
    zip_code = forms.CharField(label = 'zip_code')
  
    
    class Meta:
        model = Profile
        fields = ('image', 'gender', 'contact', 'address_line_1', 'address_line_2', 'street', 'state', 'zip_code')
        

class UploadForm(forms.ModelForm):
    name = forms.TextInput()
    price = forms.DecimalField()
    image = forms.ImageField()
    description = forms.TextInput()
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = Product
        fields = ['name', 'price', 'image', 'description', 'category']
        

User = get_user_model()

store/views/business.py
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from ..models import Profile
from django.core.exceptions import ObjectDoesNotExist
from store.backends import User
from ..forms import ProfileForm
from store.models import *
from store.forms import *
 

@login_required
def profile(request):
    profile = None
    try:
        profile = request.user.profile
        form = ProfileForm(instance=profile)
    except ObjectDoesNotExist:
        profile = None
        form = ProfileForm()

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('staff:account')

    return render(request, 'business/Profile.html', {'form': form, 'profile': profile})

@login_required
# @admin_only
def dashboard(request):
    products = Product.objects.all()
    customers = Customer.objects.all()
    orders = Order.objects.all()
    total_orders = orders.count()
    total_products = products.count()
    total_customers = customers.count()
    
    
    context = {'products':products,'customers':customers,'total_products':total_products,'total_customers':total_customers,'total_orders':total_orders}
    templates = loader.get_template('business/dashboard.html')
    return render(request,'business/dashboard.html',context)



@login_required
# @admin_only
def businesscustomer(request,pk):
    customer = Customer.objects.get(id = pk)
    orders = customer.order_set.all()
    templates = loader.get_template('business/businesscustomer.html')
    context ={
        'customer':customer,
        'orders':orders
    }
    return render(request, 'business/businesscustomer.html',context)


def upload(request):
    if request.POST:
        forms = UploadForm(request.POST, request.FILES)
        print(request.FILES)
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    return render(request, 'business/upload.html',{'form': UploadForm})

def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    form = UploadForm(instance=product)
    if request.POST:
        forms = UploadForm(request.POST, instance=product)
        
        if forms.is_valid():
            forms.save()
        return redirect('business:dashboard')
    context = {'form': form}
    return render(request, 'business/upload.html',context)

def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method =='POST':
        product.delete()
        return redirect('business:dashboard')
    context ={'product':product}
    return render(request, 'business/delete.html',context)

store/templates/customer/Profile.html
{% extends "staff/master.html" %}
{% load static %}


{%block title%} Profile {%endblock%}

{% block content %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'customer:dashboard' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:account'%}">PROFILE</a></li>
    </ul>
</nav>


<div class = 'customer'>
<div class = 'customer1'>
<form method="post" action="{% url 'customer:profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class = 'circular-image'>
    {{ form.non_field_errors }}
    {% if user.profile.image %}
        <img src="{{ user.profile.image.url }}" alt="Profile Image">
    {% endif %}
    {{ form.image }} 
    </div> 
    <label for="id_image">Upload Photo:</label> 
    <input type="file" id="id_image" name="image" accept="image/*">
    <br></br>
    <label for="id_gender">Gender:</label>
    {{ form.gender }}
    <br></br>
    <label for="id_contact">Contact:</label> 
    {{ form.contact }}
    <br></br>
</div>
    <div class = 'customer2'>
    <label for="id_address_liane_1">Address Line 1:</label>
    {{ form.address_line_1 }}
    <br></br>
    <label for="id_address_liane_2">Address Line 2:</label>
    {{ form.address_line_2 }}
    <br></br>
    <label for="id_street">Street:</label>
    {{ form.street }}
    <br></br>
    <label for="id_state">State:</label>
    {{ form.state }}
    <br></br>
    <label for="id_zip_code">Zip_Code:</label>
    {{ form.zip_code }}
    <br></br>
</div>
<br></br>
<button type="submit" class = 'submit-button'>Save</button>

</form>

</div>

{% endblock %}

store/templates/customer/account.html
{%extends 'staff/master.html'%}
{%load static%}

    {%block title%}
    ACCOUNT
    {%endblock%}


{%block content%}

<link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}">
<nav>
    <ul>
       <li><a href="{% url 'staff:homepage' %}">HOME</a></li>
       <li><a href="{% url 'staff:about' %}">ABOUT US</a></li>
       <li><a href="{% url 'staff:contact' %}">CONTACT US</a></li>
        <li><a href="{% url 'staff:services' %}">SERVICES</a></li>
       <li style="float:right"> <a href="{% url 'staff:account'%}">PROFILE</a></li>
    </ul>
</nav>

<div class = 'account_customer'> 
        <div class = "account_user">   
        <div class="account_info">
        <div class = "circular-image">
        <img src="{{ profile.image.url }}" alt="Profile Image">
        </div>
        <br> 
        <p class = 'address-text'>Email: {{ email }}</p>  <br>
        <p class = 'address-text'>Name: {{ first_name }} {{ last_name }}</p>  <br>
        <p class = 'address-text'>Username: {{username}}</p><br>
        <p class = 'address-text'>Date of Birth: {{ profile.date_of_birth }}</p><br>
        <p class = 'address-text'>Gender: {{ profile.gender }}</p><br>
        </div>

        
        <div class="account_personal">  
        <p><font size = '12' color = 'orange'>Personal</font></p><br>
        <p class = 'large-text'>Gender: {{ profile.gender }}</p><br>
        <p class = 'large-text'>Contact: {{ profile.contact }}</p><br>
        <p class = 'large-text'>Zip Code: {{ profile.zip_code }}</p><br>
        <p class = 'large-text'>Address Line 1: {{ profile.address_line_1 }}</p><br>
        <p class = 'large-text'>Address Line 2: {{ profile.address_line_2 }}</p><br>
        <p class = 'large-text'>Street: {{ profile.street }}</p><br>
        <p class = 'large-text'>State: {{ profile.state }}</p><br>
        </div>
        </div>
    
<a href="{% url 'staff:update_user' %}"><button type="submit"  class = "submit-account">Edit Profile</button></a>
</div>
{%endblock%}




       

       

store/templates/customer/cart_summary.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href={% static "css/dashboard.css"%}>
        <link rel="stylesheet" href={% static "css/main.css"%}>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body class=''>
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        <div class='sidebar'>
            <h1 class='logo'><img src='{% static "img/LOGO.JPG"%}'></h1>
 
            <div class='sidebar-menu'>
                
                <a href='{% url 'staff:contact'%}'><ion-icon name='chatbubbles-outline'></ion-icon>Contact Us</a>
                <a href='{% url 'staff:about'%}'><ion-icon name="people-outline"></ion-icon>About Us</a>
                <a href='{% url 'staff:web_settings'%}'><ion-icon name='Settings-outline'></ion-icon>Settings</a>
                <a href='{% url 'staff:account'%}'><ion-icon name='person-outline'></ion-icon>Profile</a>
            </div>
            <div class='sidebar-logout'>
                <a href='{% url 'staff:login'%}'><ion-icon name='log-out-outline'></ion-icon>Logout</a>
            </div>
        </div>
        
        <div class='main'>
            <div class='main-navbar'>
                <ion-icon class='menu-toggle' name='menu-outline'></ion-icon>
                <form action='{% url 'customer:search' %}' method='GET'>
                    <div class='search'>
                        
                        <input type='text'name = 'q' placeholder = 'What would you like' required>
                        <button class='search-btn' type='submit'>Search</button>
                        
                    </div>
                    </form>
            
                <div class='Profile'>
                   
                    <span id ='cart_quantity'><strong>{{cart|length }}</strong></span>
                    <a class='user' href='{% url 'customer:cart_summary' %}'><ion-icon name='cart-outline'></ion-icon></a>
                </div>
            </div>
            <div class='main-highlight'>
                <div class='main-header'>
                    <h2 class='main-title'>Shopping Cart</h2>
                    
                </div>
                <div class='highlight-wrapper'>
                    <div class='highlight-card'>
                        <img class='highlight-img'scr="C:\\Users\\hp\\OneDrive\\Desktop\\h jv st\\img\\Black White Simple Monochrome Initial Name Logo.jpg">
                </div>
            </div>
        </div>

        <div class='main-menus'>
            <div class='main-filter'>
            <div>
                <h2 class='main-title'>View your Cart</br></h2>
                
            </div>
            
            </div>
            <hr class='divider'>
            <div class="row">
            <div class="col-lg-12">
                <div class="box-element">
                    <a class="btn btn-outline-dark" href="{% url 'customer:dashboard' %}">&#x2190; Continue </a>
                    <br>
                    <br>
                    <table class="table">
                        <tr>
                            
                            <th><h5>Total:<strong>UGX {{ totals }}</strong></h5></th>
                            <th>
                                <a style="float:right; margin:5px;" class="btn btn-success" href ="{% url "customer:checkout" %}">Checkout</a>
                            </th>
                        </tr>
                    </table>
                </div>
                <br>
                <div class="box-element">
                    <div class ="cart-row">
                        <div style="flex:2"></div>
                        
                        <div style="flex:2"><strong>Item</strong></div>
                        <div style="flex:1"><strong>Price</strong></div>
                        <div style="flex:1"><strong>Quantity</strong></div>
                        
                        <div style="flex:1"><strong>Delete Item</strong></div>
                    </div>
                    {% if cart_products %}

                        {% for product in cart_products %}
                        <div class ="cart-row">
                            <div style="flex:2"><img class="row-image" src="{{product.imageURL}}"></div>
                            <div style="flex:2">{{product.name}}  </div>
                            <div style="flex:1">{{product.price}}  </div>
                            <div style="flex:1">
                                <p class="quantity">{{ vlaue }}</p>
                                <div class="quantity">
                                    
                                    

                                       
                                            {% for key, value in quantities.items %}
                                               {% if key == product.id|slugify %}
                                               <strong>
                                                   <p selected>X{{ value }} </p>
                                               </strong>
                                               {% endif %}
                                            {% endfor %}
                                       
                                        
                                </div>
                                    
                            </div>
                            

                            

                            <button type='button' data-index='{{product.id}}' class='btn btn-danger delete-product'>Remove</button>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="container">
                            <div class="card">
                                
                                <img src="{% static 'img/cart.jpg' %}" alt="">
                                <h4>Your cart is empty!</h4>
                                <h6>Add item to it now</h6>
                                <button class="btn btn-primary">Shop Now</button>
                            </div>
                        </div>
                    {% endif%}
                </div>
            </div>

        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>   
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        {% comment %} <script type='text/javascript' src="{% static 'js/cart.js' %}"></script> {% endcomment %}
        <script src={% static "js/app.js"%} ></script>
        <script>
            // Update Item
            $(document).on('click','.update-cart', function(e){
                e.preventDefault();
                var productid = $(this).data('index');
                $.ajax({
                    type:'POST',
                    url: '{% url "customer:cart_update" %}',
                    data: {
                        productid : $(this).data('index'),
                        product_qty: $('#select'+ productid + 'option:selected').text(),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: 'post'
                    },
            
                    success: function(json){
                        console.log(json)
                        document.getElementById('cart_quantity').textContent = json.qty
                        location.reload();
                    },
                    error: function(xhr, errmsg, err){
            
                    },
            
                });
            })


            //Delete Item
            $(document).on('click','.delete-product', function(e){
                e.preventDefault();
                var productid = $(this).data('index'); // Get the product ID from data attribute
                
                $.ajax({
                    type: 'POST',
                    url: '{% url "customer:cart_delete" %}',
                    data: {
                        product_id: productid, // Send the product ID to the server
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: 'post'
                    },
                    success: function(json){
                        // If the server successfully deletes the item from the database, reload the page or update the UI accordingly
                        location.reload();
                    },
                    error: function(xhr, errmsg, err){
                        // Handle error if necessary
                    }
                });
            });
            
            
        </script>
    </body>
</html>

store/templates/customer/customer.html
{% extends 'staff/master.html' %}

{% block content %}

  <h2>Sign up for a customer</h2>
  <p class="lead">Select below the type of account you want to create</p>

{%endblock%}